name: API Météo CI/CD

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Configuration de Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Installation des dépendances
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Exécution des tests
      run: |
        pytest

  build_and_push:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
    - uses: actions/checkout@v3
    - name: Configuration de Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Construction et export
      uses: docker/build-push-action@v4
      with:
        context: .
        tags: api-meteo:latest
        outputs: type=docker,dest=/tmp/api-meteo.tar
    
    # Décommentez ce qui suit pour pousser vers Docker Hub
    # - name: Connexion à Docker Hub
    #   uses: docker/login-action@v2
    #   with:
    #     username: ${{ secrets.DOCKERHUB_USERNAME }}
    #     password: ${{ secrets.DOCKERHUB_TOKEN }}
    # - name: Pousser vers Docker Hub
    #   uses: docker/build-push-action@v4
    #   with:
    #     context: .
    #     push: true
    #     tags: votreutilisateur/api-meteo:latest 